version: '3'

networks:
  backend:

    null
services:

  postgres_db:
    image: postgres
    container_name: postgres_db
    networks:
      - backend
    environment:
      - bind-address=0.0.0.0
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

  python_app:
    build: .
    networks:
      - backend
    environment:
      - DBHOST=postgres_db
    depends_on:
      - postgres_db
    ports:
      - 8888:8888
    command: >
      bash -c "sleep 30 && python create_tables.py && uvicorn main:app --host
      0.0.0.0 --port 8888"
